[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "OpenSSL",
    "Zlib",
    "MPL-2.0",
    "0BSD",
]
copyleft = "warn"

[bans]
multiple-versions = "warn"
deny = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
